CXX=g++
CXXFLAGS=-Wall -Wextra -Werror -pedantic -std=c++14 -Weffc++
CXXLIBS=
LDFLAGS=-L.

EXE=a

.PHONY: GUI all clean

all: a

GUI: all
	@echo -n "building gui "
	@sleep 1
	@echo -n "."
	@sleep 1
	@echo -n "."
	@sleep 1
	@echo -n "."
	@sleep 1
	cp a hra2017_gui

CLI:
	cp a hra2017_cli


clean:
	@echo "cleaning like mexican cleaning lady"
